### ISSUE TITLE
Building fresh v.0.24.1 template with Giraffe and Fable.Remoting fails

### ISSUE THREAD

**Issue by samme78** [SAFE-Stack/SAFE-template#116]
On Windows 10

`dotnet new -i SAFE.Template`
`dotnet new SAFE --server giraffe --layout fulma-cover --remoting --deploy docker`
`fake build --target run`

After a while I get the following error:

![error](https://user-images.githubusercontent.com/13017677/42539018-f7855ec6-8499-11e8-9b25-758394b78b28.png)

Dotnet and Fake versions:

```
C:\gitprojects\TournamentDirector>dotnet --version
2.1.301

C:\gitprojects\TournamentDirector>fake --version
FAKE 5 - F# Make (5.1.0)
```

**Comment by samme78** [comment]
Attached is the complete console output from the commands in the previous post.

[Failed_Safe_build.txt](https://github.com/SAFE-Stack/SAFE-template/files/2182259/Failed_Safe_build.txt)

**Comment by Zaid-Ajaj** [comment]
Hi there @samme78 , I am able to reproduce the same error on Windows 10 with dotnet 2.1.300 

The reason is the dependency `Fable.Remoting.Server` is being pinned to version `4.1.1` which is the latest version that has breaking changes (we will upgrade soon) 

For now, as a workaround you can pin `Fable.Remoting.Server` to version `3.6` (the compatible version) by adding this entry to your server group:
```
nuget Fable.Remoting.Server ~> 3.6
```
so `paket.dependencies` becomes:
```
group Server
    storage: none
    source https://api.nuget.org/v3/index.json

    nuget FSharp.Core
    nuget Giraffe ~> 1
    nuget Microsoft.AspNetCore
    nuget Microsoft.AspNetCore.StaticFiles
    nuget Fable.Remoting.Server ~> 3.6
    nuget Fable.Remoting.Giraffe ~> 2.7

group Client
    storage: none
    source https://api.nuget.org/v3/index.json

    nuget Fable.Core
    nuget Fable.Elmish.Debugger
    nuget Fable.Elmish.React
    nuget Fable.Elmish.HMR
    nuget Fable.Remoting.Client ~> 2.5.1
    nuget Fulma

    clitool dotnet-fable

group Build
    storage: none
    source https://api.nuget.org/v3/index.json

    nuget FSharp.Core 4.3.4 // https://github.com/fsharp/FAKE/issues/2001
    nuget Fake.Core.Target
    nuget Fake.DotNet.Cli
    nuget Fake.IO.FileSystem

```
delete `paket.lock` and run `fake build --target run` again
