### ISSUE TITLE
Use sass instead of css

### ISSUE THREAD

**Issue by vasily-kirichenko** [SAFE-Stack/SAFE-template#140]
I have problems using Fulma.Extentions until converted the css file to sass (and added css-, sass and style-loader via yarn). 

What are the reasons the template uses plane css?

**Comment by theimowski** [comment]
It's mainly because https://dansup.github.io/bulma-templates/ use plain css so it was easier for me to grab the stylesheets when porting the bulma templates to SAFE. Curious to hear other's opinion on that - I know there's also LESS, so I'm not sure if it's good to lock SAFE users to specific CSS preprocessor

**Comment by rfrerebe** [comment]
Hello,

I did a quick repo with SAFE stack and SCSS template
https://github.com/rfrerebe/SAFE-Stack-With-SCSS

It works with Fable 1, but should be fairly simple to port to Fable 2 if needed.
