### ISSUE TITLE
add typescript integration

### ISSUE THREAD

**Issue by 0x53A** [SAFE-Stack/SAFE-template#147]
I want to push a bit how easy it is to integrate typescript into fable.

What would you think about adding a new flag ``--txpescript``?

This would configure webpack and drop one typescript file into the project.

In the .tsx I would define a simple React component, and import it from Fable.

**Comment by theimowski** [comment]
Do you have an example of application using this approach?

**Comment by 0x53A** [comment]
I'm doing it to use babylonjs because ts2fable can't handle it.
i created a small wrapper in typescript, then interfaced with that in F#.

I can publish an example "soon".

**Comment by functionalprogrammer** [comment]
Hi @0x53A. Unfortunately, this feature will not be included in SAFE template out-of-the-box. However, we might consider publishing a recipe for it in SAFE docs. I don't entirely understand the use of having a TypeScript layer, though. Why not just write the wrapper in F# rather than writing it in TypeScript and interfacing it in F#?
