### ISSUE TITLE
Change default build target to Run?

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-template#178]
This would let people start with just `fake run` I guess, rather than `fake build -t Run`?

**Comment by theimowski** [comment]
I've been thinking about this. 
If we make `Run` the default target then both `fake run` and `fake build` would trigger the "interactive" mode, which can make things a bit unclear since `run` subcommand is technically not the same as `run` target in build script.
Wondering whether we can come up with a "standard" way of naming the basic FAKE targets in a SAFE project. I saw people are also using `watch` name instead of `run` for this target.

**Comment by theimowski** [comment]
Closing, I think the `dotnet fake build --target run` is by now well established
