### ISSUE TITLE
Minify-plugin (terser-webpack-plugin) is not inlining code correctly

### ISSUE THREAD

**Issue by dbrattli** [SAFE-Stack/SAFE-template#190]
Project using SAFE-template (https://github.com/rommsen/Fable.Reaction.Playground) only works in debug, but not production (-p) mode. The problem is caused by the minify plugin not inlining code correctly. To make it work we need to disable inlining in webpack config like this:

```js
        minimizer: isProduction ? [new MinifyPlugin({
            terserOptions: {
              compress: {
                  inline: false
              }
            }
          })] : []
    },
```
`inline: 1` actually works, but not `inline: 2`. I think this is scary. According to @alfonsogarciacaro we should instead compile to ES5 (basically the default when using @babel/preset-env) and use the default Webpack minification.

**Comment by theimowski** [comment]
Is this an issue only when `--pattern reaction` is used?

**Comment by theimowski** [comment]
What's exactly the issue with production mode here? I cloned the mentioned repo, added Docker targets as per the template, and managed to get it running via Docker image, which uses -p flag.

**Comment by dbrattli** [comment]
It is an issue when Fable somehow generates code that the minifyer cannot translate correctly. I don't know exactly what goes wrong. The problem I found is on line 210. https://github.com/dbrattli/Reaction/blob/master/AsyncRx/src/Transform.fs#L210  With `-p` the function `action` is never called. The lines after 210 is also never called. Everything just stops.

The mentioned repo now has a bugfix in webpack.config.js. Change this line to `true` and try again: https://github.com/rommsen/Fable.Reaction.Playground/blob/master/src/Client/webpack.config.js#L73

**Comment by theimowski** [comment]
How do you determine if we generate ES5 / ES6 ? 
I mean how do you configure that in webpack + fable?

**Comment by alfonsogarciacaro** [comment]
I would compile to ES5 to get IE11 support and use the default minifier in Webpack (UglifyJS). UglifyJS author stopped working on the ES6 version because there were many edge cases, like this one. Terser was forked from UglifyJS ES6 branch, so by using it we're exposed to the corner cases. 

You can check the [Webpack-config-template](https://github.com/fable-compiler/webpack-config-template/blob/ca816618db1455440acd5612c2fca5f257435393/webpack.config.js#L19-L30) to see the Babel configuration (actually, we could change "targets" to "defaults" to stop supporting IE10. [You can check here](https://browserl.ist/) what's the browser support depending on the "targets" value.

**Comment by alfonsogarciacaro** [comment]
BTW, it seems actually [Terser is (now?) the default minifier for Webpack](https://twitter.com/wSokra/status/1069548921469444096) (didn't know that). So probably it's not necessary to add it explicitly.
