### ISSUE TITLE
Add Storage Type Provider to Azure template

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-template#196]
We should include the Azure Storage TP to the template once it reaches v2 with support for net core.

**Comment by isaacabraham** [comment]
@theimowski is there a reason why some of the `#if` definitions in the template are preceded by `//` e.g. [here](https://github.com/SAFE-Stack/SAFE-template/blob/master/Content/src/Server/ServerSaturn.fs#L19)?

**Comment by theimowski** [comment]
I think this is due to historical reasons. IIRC initially I had to add custom configuration to use conditional in [F# sources](https://github.com/SAFE-Stack/SAFE-template/blob/master/Content/.template.config/template.json#L501-L523) 

I'll create a separate issue for this as it should be cleaned anyway

**Comment by theimowski** [comment]
is this still relevant @isaacabraham ?
