### ISSUE TITLE
How to deploy using Docker and use a proxy rule

### ISSUE THREAD

**Issue by halcwb** [SAFE-Stack/SAFE-template#222]
I want to run a safe stack app on a server using a docker container. So, I have created a container which I downloaded and started on my server. However, I want to use a proxy rule such that a request to: http://mydomain.net/subdomain/ is routed to localhost:8085. But obviously the request is in that case:
`mydomain/subdomain/` instead of `/`. 
I also posted my question on [StackOverflow](https://stackoverflow.com/questions/54421388/use-sub-domain-proxy-rule-to-host-a-safe-stack-application-deployed-by-docker).

**Comment by theimowski** [comment]
I think the issue is highly related to Docker configuration - fact that you're using SAFE Stack app shouldn't have any impact here. 
Are you sure you're referring to subdomain in this case? The [subdomain](https://en.wikipedia.org/wiki/Subdomain) in this case would be `subdomain.mydomain.net` rather than `mydomain.net/subdomain` - the latter case is just a path in context of an [URL](https://en.wikipedia.org/wiki/URL)

**Comment by halcwb** [comment]
This shows my ignorance with regard to the http protocol. However, I managed to get things working by adding a virtual host and pointing the proxy rule to the domain itself. The next problem I ran into is that the client side fetch uses the localhost at times, which obviously fails, and using different browser versions uses the correct domain.ext name for the domain.ext/api/init fetch.

**Comment by halcwb** [comment]
Thanks. I think I got it.
