### ISSUE TITLE
SAFE template without paket

### ISSUE THREAD

**Issue by ijsgaus** [SAFE-Stack/SAFE-template#246]
Can i create SAFE solution only on dotnet core, without paket?

**Comment by forki** [comment]
Paket works on dotnet core.

Ivan Simongauz <notifications@github.com> schrieb am Do., 11. Apr. 2019,
21:23:

**Comment by theimowski** [comment]
Yup paket does work on dotnet core.
SAFE template uses paket for pinning dependencies, however one doesn't need to have paket if just wants to try SAFE out - the template doesn't bundle it at the moment.

If you're asking about whether you can manage your dependencies using default NuGet client, the answer is no - we strongly advise to have all the dependencies pinned and that's why use paket under the hood.
