### ISSUE TITLE
Carriage Return at build.sh

### ISSUE THREAD

**Issue by Kludex** [SAFE-Stack/SAFE-template#25]
The file build.sh has the character '\r'. It doesn't work on my Ubuntu 16.04. 
I needed to use this command:
tr -d '\r' < infile > outfile

**Comment by theimowski** [comment]
You sure? I think this should be handled by your git checkout config

**Comment by jacereda** [comment]
I faced the same problem on Mac right now.

**Comment by theimowski** [comment]
Ok so it turns out, according to https://github.com/dotnet/templating/issues/1248 that line endings are same as in original files going to template upon building. As I'm developing on Win, i had autocrlf set to true, so `build.sh` files ended in the template package with CRLF. This should be fixed in 0.4.1
