### ISSUE TITLE
Suggestion: `.sln` file in root directory instead of `src`

### ISSUE THREAD

**Issue by iNecas** [SAFE-Stack/SAFE-template#260]
I was surprised after creating a new app with `SAFE-template`, to have the solution file in `src` dir instead of the `root` one, as seems to be a standard in the fsharp world (https://github.com/fsharp/fsharp, https://github.com/fsprojects/FSharp.Formatting, https://github.com/fsharp/FAKE, https://github.com/fsprojects/Paket).

This is not only cosmetic thing, but actually makes it harder to work with in real world, as some IDEs (at least Rider), consider the directory with `.sln` file the root dir, with consequences such as FAKE and paket scripts not actually showing up in the IDE.

Any reason for doing it this way and any chance to change it's location?

**Comment by theprash** [comment]
I would prefer it to be in the root as well. And if possible it should have the name of the parent folder (the assumed project name) instead of always being called `safe.sln`. Is that possible with dotnet templates?

Note that the FAKE and paket files would still needed to be explicitly added to the solution file in the template to show up in Visual Studio, even if it was moved.

**Comment by theimowski** [comment]
Yes we can move the solution file to root directory. @theprash  I believe this should be possible - maybe https://github.com/dotnet/dotnet-template-samples demos how to do that?
Any volunteers to contribute?
