### ISSUE TITLE
Fulma extensions are missing styles

### ISSUE THREAD

**Issue by Freymaurer** [SAFE-Stack/SAFE-template#261]
I tried installing the [fulma tooltip extension](https://fulma.github.io/Fulma/#fulma-extensions/tooltip) and followed the installation instrcutions:
> yarn add bulma-tooltip@2.0.2
>
I also added the paket.dependencies:
```
group Client
    source https://api.nuget.org/v3/index.json
    framework: netstandard2.0
    storage: none
    nuget Fable.Core ~> 2
    nuget Fable.Elmish ~> 2
    nuget Fable.Elmish.Debugger ~> 2
    nuget Fable.Elmish.React ~> 2
    nuget Fable.Elmish.HMR ~> 2
    nuget Fable.React ~> 4
    nuget Fulma
    nuget Fulma.Extensions.Wikiki.Tooltip
```
And also to the pacet.references in the Client folder:

```
group Client
    FSharp.Core
    Fable.Elmish.Debugger
    Fable.Elmish.React
    Fable.Elmish.HMR
    Fable.Core
    Fulma
    Fulma.Extensions.Wikiki.Tooltip
```

I was then able to use the mentioned tooltip functions but apparently there are no functional styles automatically installed. So i don't get any tooltips shown on my localhost.
For testing i used the example code on the fulma tooltip page.

**Comment by MangelMaxime** [comment]
@Freymaurer Did you include the `bulma-tooltip` style in your application?

[Example](https://github.com/Fulma/Fulma/blob/master/docs/scss/main.scss#L42)

if you used the template as it is, I guess you will need to include it using a CDN. For example, this is how SAFE template is including Bulma [source](https://github.com/SAFE-Stack/SAFE-template/blob/master/Content/src/Client/index.html#L9).

But I would encourage you to include `bulma` via `package.json` too so you can customize Bulma using variables, add extensions easily. Manage the version using `yarn` or `npm` instead of manually handling the version.

**Comment by Freymaurer** [comment]
Thank you for your quick answer! I am a beginner for web development, so i am not sure if i understood everything correct, but here is what i have:

- my package.json contains the following:
```
    "dependencies": {
        "bulma-tooltip": "2.0.2"
    }
```
- my index.html referenced the following:
`    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-tooltip@2.0.2/dist/css/bulma-tooltip.min.css">`
A more experienced friend helped me out and fixed the tooltips by additonally referencing the following:
`    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css">`

So for me it works now, but i thought maybe you would want to know about this.

**Comment by MangelMaxime** [comment]
This is totally normal behaviour.

When adding `bulma-tooltip` to your `package.json` you just add it to your dependencies list but don't include it in your application.

A bit like adding a dependency to `paket.dependencies` but not to `paket.references`.

------------

`bulma-tooltip.min.css` only include the CSS for the tooltips. So that's why you need to include `bulma.min.css` too.

That's why in my example I have:

```fs
@import '../../node_modules/bulma/bulma';
@import "../../node_modules/bulma-tooltip/dist/css/bulma-tooltip.sass";
```

@theimowski For me this issue can be closed, this is related to standard `.css` usage. In theory, the next version of Fulma documentation should be more descriptive about it. And will ask people to read the original package documentation too which should explains how to include the style in the user project.

**Comment by kerams** [comment]
>When adding bulma-tooltip to your package.json you just add it to your dependencies list but don't include it in your application.
>
>A bit like adding a dependency to paket.dependencies but not to paket.references.

This is a key piece of information. I thought that Webpack automatically extracts and bundles every dependency (JS as well as CSS) from `package.json`. Thanks.

**Comment by theimowski** [comment]
Perfect, thanks @MangelMaxime for helping here
