### ISSUE TITLE
Bring back global.json

### ISSUE THREAD

**Issue by forki** [SAFE-Stack/SAFE-template#268]
we should bring back global.json since it forces dev system and CI to run with same dev tools and compiler version.

**Comment by isaacabraham** [comment]
## Pros
* Guaranteed same tools / compiler on build and CI

## Cons
* Maybe makes CI more complex - need to install a specific version of dotnet even if you have a more recent version on the CI environment
* Slower and more complicated first-time install of SAFE - assume you have installed latest version of SDK, you then try SAFE and watch as it fails because you didn't install a *specific* version of dotnet - then you have to go back and install that version etc.
* Increase disk space (sounds like nothing but there are so many versions of dotnet out there and each one is a few hundred MB - and it all adds up)

My personal view is that we shouldn't have it on by default - possibly as an optional add-in to the template (again), or perhaps just documentation. Happy to listen to other views though.

**Comment by forki** [comment]
the thing is: people can always choose to set another version in that file. It's just important that you set one. Similar with the lock files in yarn or paket. It's not that important which one you choose, but shit needs to work together.

Regading the Cons: 

* We have proper scripts that install the correct SDK on demand for the CI. it's not that hard. 
* If you have the latest version then you can just set it in the global.json and be done with it. This is how the rest of the ecosystem works as well.
* If you have very old SDK version installed then your wuild will break for various reasons anyway.

**Comment by isaacabraham** [comment]
Latest version - that's a moving target, with new versions every few weeks, which means people having to update the file every time they install a new version.

I've not heard lots of people complaining about this yet - for most people the first-time use experience has been pretty good (and I think that that's more important than the CI/CD process) - hence my thought that making it an optional file might be preferable.

**Comment by forki** [comment]
well I don't think first time use is more important in a stack that we recommend to be the thing for rock solid production apps. 

That said: we can still try to make first time use Ok. Maybe we can detect the installed SDK in the templating process or something. Or make it super obvious in the docs that this is a requirement.
There are many things that we can do to mitigate - but this move to remove it was just punting on the problem.

**Comment by theimowski** [comment]
The removal of global.json was also related to FAKE target installing dotnet version from global.json
I decided to remove both back in a day as we had couple reports of "unwanted installs" from users who were already on a newer dotnet version

The main issue was that FAKE checked exact version from global.json so there was no way to specify "bigger than" version - not sure if anything changed in that regards since.

I'm still not convinced we should bring it back - sure, there are benefits of having .net core version pinned, however I believe experienced users know how to do that when necessary.
We list .NET Core 2.2 in prerequisites right now, so if we add extra note to quickstart docs to adjust global.json it might be misleading for newcomers?

**Comment by forki** [comment]
Again: newcomers are important. But making this thing rock-solid and a proper advice should be the no. 1 concern. Letting dotnet sdk version to chance is definetely something that we should not recommend to do.

**Comment by Nhowka** [comment]
I'm not sure how that might work with heroku buildpack. Also I'm on the side that people using CI don't need that much hand holding and can create the file themselves with a recommendation if they need it.

**Comment by forki** [comment]
the whole point of the thing is hand holding. Giving advince how to structure your solution. Making sure stuff fits together. Making sure tools work together. Having companies giving support for stuff that's mostly working in the same fashion.

**Comment by theimowski** [comment]
@Nhowka what's specific about heroku here? If I understand @forki correctly, the suggestion is to tell fake script to download specific .net sdk and use it for building the projects within fake script

What if we added a post-install script to the template that would parse `dotnet --version` if installed and if it's newer than the one in global.json then overwrite it?
That would be a win-win right?

**Comment by Nhowka** [comment]
The build is done by the buildpack, where it will generate a standalone binary file that will just run when the instance is started. I'm not sure if it can download and then use a the specific version. The path definition can get a little fuzzy and new commits could use a different version if the buildpack is updated.

I may be worried about nothing, maybe it will just work.

**Comment by forki** [comment]
@theimowski no I'm not talking about fake. I'm talking about dotnet tools like dotnet build using the correct version from the global.json file. This includes the correct F# compiler, the correct version of nuget.exe (which is still used under the hood) and so on. If you don't have a global.json then you get a random compiler version. Basically whatever is found in your path. How can we possibly endorse that and still talk about how important it is to use lock files for deps?

Regarding FAKE: it was only a convenience feature that the fake script did download the matching sdk version automatically. This avoided the problem that people had to install the sdk on CI servers. Due to some bugs, long download times and especially due to bad communication people saw it as inconvenient.

**Comment by isaacabraham** [comment]
@theimowski basically yes, that's the issue. I believe there was a recent discussion about allowing global.json to specify a minimum (and max?) version (which would solve my concerns) but for now I am not overly keen to add this back in. As @Nhowka says, with a a recommendation they can add it. I'm not hearing much feedback about this causing problems for people to be honest - in fact the last time I remember it was the opposite - someone added a new version of DNC and couldn't understand why their SAFE app wasn't getting the new stuff.

**Comment by forki** [comment]
Sigh

**Comment by forki** [comment]
related: https://github.com/dotnet/cli/issues/11499

**Comment by theimowski** [comment]
@forki let's say that we add just the global.json with current SDK version (2.2.107?) but don't add part where fake installs that version - what would that change compared to current situation? I'm trying to understand how global.json actually works from SAFE project point of view

**Comment by forki** [comment]
current SDK is 2.2.300

if we only add the global.json then we have unfortnate situation that you need exactly that version installed or nothing works at all. So users then need to install that version or change the global.json.
On dev machine this can be seen as OKish - installing a new SDK is straight forward. On CI servers it can be really annoying

**Comment by theimowski** [comment]
right then IMO given current state of matter, we should leave template as is, and instead add a note to quickstart docs: something between those lines "consider adding a global.json file (link) to pin .NET Core version for deterministic builds"

**Comment by theimowski** [comment]
global.json is now in both default and minimal options as of v2
