### ISSUE TITLE
Thoth Fetch Fable dependency fails on Admin template

### ISSUE THREAD

**Issue by voronoipotato** [SAFE-Stack/SAFE-template#320]
```
ERROR in ./.fable/Thoth.Json.3.4.1/Encode.fs
Module Error (from ./node_modules/fable-loader/index.js):
C:/Users/awball/Documents/Projects/AssetMana/.fable/Thoth.Json.3.4.1/Encode.fs(437,28): (437,60) error FABLE: Cannot resolve System.Enum.GetUnderlyingType
 @ ./src/Client/Client.fs 58:0-171 300:115-121 300:228-233 300:335-342 305:25-77
 @ ./src/Client/Client.fsproj
 @ multi ./src/Client/Client.fsproj
```

I was able to get it to work by using a later version of fable-compiler. Looks like a lot of dependencies are old. I also updated the .netcore to 3.0 and things do work now but it looks like it fails out of the box.

**Comment by MangelMaxime** [comment]
I just checked the template does work out the box. I think you upgraded the dependencies when doing the switch to .netcore to 3.0.

Out of the box, the template is using `Thoth.Json (3.3)`.

However, I think the template should be upgraded to `Thoth.Json 3.4` and the latest version of `fable-compiler` because not everyone knows that enum reflection API is a recent addition.

**Comment by voronoipotato** [comment]
It works fine with 3.0, should we switch to it?

**Comment by theimowski** [comment]
update to 3.0 is WIP https://github.com/SAFE-Stack/SAFE-template/pull/318

**Comment by theimowski** [comment]
3.0 support has been released in v1.19 - can you check if it works now OOTB?

**Comment by voronoipotato** [comment]
I'll have time this weekend :)

**Comment by theimowski** [comment]
Closing - should no longer be an issue in v2
