### ISSUE TITLE
Add chmod post action for Unix 

### ISSUE THREAD

**Issue by theimowski** [SAFE-Stack/SAFE-template#33]
https://github.com/dotnet/templating/wiki/Post-Action-Registry#change-file-permissions

https://github.com/SaturnFramework/Saturn.Template/pull/2

**Comment by rmunn** [comment]
Fixed in PR #34.

**Comment by rmunn** [comment]
This issue should be reopened since #34 had to be reverted due to #36. Once https://github.com/dotnet/templating/issues/1421 gets addressed and I find out how to set a condition that will actually work correctly, I'll be able to make this post-action script only run on Linux or OS X. In the meantime, this issue should still be open.

**Comment by theimowski** [comment]
Fixed by #37
