### ISSUE TITLE
SAFE + Elmish entrypoint questions

### ISSUE THREAD

**Issue by Jmaharman** [SAFE-Stack/SAFE-template#359]
I've been having thoughts around SAFE for a while, but I haven't been able to glean any obvious answers from other sources. I started writing this on the "Roadmap and request for feedback" issue, but the more I wrote, the more it felt like I was asking for approaches people have taken to my problem.

To give you a bit of context, where I work we create internal web based tools for companies that help their staff do their jobs. We are C# based, and we use ASP.NET MVC with Razor for a lot of what we do. We always always start with basic Razor pages, those Razor pages may have a sprinkling of JS on them, something you'd do with jQuery / vanilla JS or perhaps more recently Alpine.js. When a page becomes complex we may use Vue, or React for that specific content instead. In those scenarios we would communicate to the backend using ajax requests or SignalR depending on the use case.

The complex pages are often the administration areas, but not always, there are some other interactions that require something more interactive and dynamic. However those scenarios are less common.

_Before I continue I should point out that I realise SAFE is a opinionated composition of F# tooling to help create a good developer experience, and that some of what I mention aren't SAFE problems, however as SAFE users you probably have good insights into other approaches that can be taken._

When reading about SAFE originally it sounded great, reusing skills for both frontend and backend was something I've been after for a while, but was always out of reach with a team of C# devs because there was not enough buy in to get that out of nodejs, nor was I truly sure that was the correct approach. Additionally, the ability to re-use my existing knowledge of webpack and the JS ecosystem on the whole meant the concept felt comfortable to me. Initially I tried to play around with the SAFE Dojo, but I didn't know enough F# to understand the syntax and what was going on. That's not SAFE's fault, I needed to go off and learn more F#. When I came back with the necessary level of knowledge to understand the syntax better it all became clearer.

I continue to read other examples provided, before I then dive in by creating a new template. Initially I liked what I saw, SAFE brought me a similar experience of what I currently have with React + TypeScript. Although I haven't touched on any communication with the server, where I believe the benefits would really shine. I start to think how I would apply it at work but this is where my problems start.

SAFE is setup with one point of entry for the application. The more pages you have, the larger your setup becomes and the larger your initial JS download becomes too. Which leads me to my first question, are developers using FunctionComponent.Lazy to help reduce the initial download size or are they asking the user to download all JS at once? Or have I missed something, and there are other techniques being used to help avoid this problem?

Not only does the entrypoint file become larger in size to download, but the amount of boilerplate required to hook up the pages / programs into the MVU grows too, which adds a lot of noise from what I can see.

If the download size can be kept managable with the use of FunctionComponent.Lazy, the boilerplate still feels problematic to me. I'd want to avoid that where possible. This is where I look at the API that Saturn provides, with the composable pipelines and routers, and wonder whether something similar could be applied to Elmish. Is that at all possible, and if so has it been attempted already?

I'd like to pivot on the above questions and ask some relating to multiple entrypoints if I may. 

On our projects where UIs are completely separate we add them as new entrypoints in the webpack configuration, and attach that React app to an element on the appropriate page. It looks like I could modify the webpack config provided in the template to replicate this. Has anyone else gone with the approach of adding additional entrypoints to the webpack configuration, or are there other approaches to avoid medium to large projects where you do not wish the only entry point of the website to be JavaScript based, e.g. some pages will render with Giraffe ViewEngine, while some will use the JS exported out of webpack and attach the React application to the page manually.

Thank you for taking the time to read this. 

John

**Comment by isaacabraham** [comment]
Hey @Jmaharman. Great points and questions I do see from time to time! Probably @MangelMaxime and @Zaid-Ajaj will have more comments on the webpack side of things, but yes, splitting into islands of JS sounds like one way to go. Other options include:

1. Do you consider some parts of the application actually in reality different apps? In which case, you can host them all in the same webserver but they are loaded in different routes e.g. mysite/admin and mysite/consumer etc.
2. Mixing and matching server-side content and client-side content is definitely an option.
3. A third option (and this is more about load times and first-use experience) is to look at SSR.

Regarding the bloat of the MVU "top level" - that's basically a "feature" of MVU in my mind i.e. messaging is explicit. This has costs in terms of some boilerplate but the flip side is that there is no magic messaging and it's pretty simple to see the flow. You can also look at creating stateful react components (I think @Zaid-Ajaj was doing something on this recently) as a way of keeping state "localised" to a component.

This does feel like something we should look to add more guidance around and possibly some libraries or tooling to provide some opinionated direction.

**Comment by Jmaharman** [comment]
Thanks for such a quick response

Regarding option 1: There are certainly times where they are completely separate functionality, the constraint being that they exist on the same domain and rely on cross cutting concerns like authorisation and perhaps user information, the typical cross cutting concerns. In what way are you imagining the composition of these different routes into the site? is that via nuget packages for each area, and composing those into single top level application? Or are we talking some form of reverse proxy sitting in front of multiple sites?

I do understand the point regarding MVU top level being more explicit, that is the F# way after all, but if these components really have no commonality between them it feels unnecessary. I know Feliz.UseElmish was released recently, this may help me simplify the top level where possible. I'll sleep on this one some more and see if the pain actually exists during development, or if I am trying to solve a problem that doesn't exist.

Regarding your last paragraph, I think having something available in the documentation could help for common questions and growth scenarios could help. Even if it was as simple as adding a few more items to the FAQ. Which reminds me that I was hesitant about using SAFE originally because I couldn't see anything obvious of how the client / server were pulled back together again for deployments. It was later when reading the FAQ that it became clear to me. I was originally worried that it would add extra work to the deployment and something extra to explain to my team, but it actually dovetails beautifully.

Thanks again

**Comment by isaacabraham** [comment]
I think this just illustrates how we need to revamp the docs to make it much clear as to what, where, when and how things are :-)

**Comment by MangelMaxime** [comment]
Hello,

I never really looked deeply in the bundle size-reduction but here are my thoughts. 

This is definitly possible to use webpack with a multi-entry point. Still, I think it can need some configuration to get the standard code not repeated in each bundle like `fable-core`, `react`, shared code/library from your project etc.

`FunctionComponent.Lazy` can help reduce the initial bundle size without modifying your `webpack.config.js` for adding a new entry point, but we are not sure of the result on a large scale. Alfonso tested it on [fulma-demo](https://github.com/MangelMaxime/fulma-demo/pull/27), and you can have a look at the discussion for more information.

It's also important to note that when using `FunctionComponent.Lazy` the developer need to understand how webpack is splitting the code to help it make a decision and be able to split the chunk the most effective way.

For example, not making an instance of a library in the global helper module but if possible at the caller site, or in a specialized helper module, etc. It's kind of what was done for `Showdown` in the PR I linked above.

------------

I have the same opinion as @isaacabraham regarding the boilerplate code. From my experience, you can't really remove it because not all `update`, `init` or `view` functions have the same contract.
What I mean is that `update` doesn't always have the signature `Model -> Msg -> Model * Cmd<Msg>`  but some times it can have `Session -> Model -> Msg -> Model * Cmd<Msg>`, `Session -> Context option -> Msg -> Model * Cmd<Msg>`, etc.

When looking at my application, if I was to write helpers to avoid boilerplate I would probably only remove 5-10% of the boilerplate and it would make my code harder to read because of having special cases due to helpers/non-helpers code.

"Stateful" component like `Feliz.UseElmish`, `Fable.React.ReactiveComponents`, etc. can probably help. They isolate from the outside world. However, you would still need to have a way to hook the session without duplicating it. By that I mean you should not store your session information in a different place in your application because they can go out of sync etc.

I guess the solution would be to pass it via the props and avoid having a global variable ^^

I took the session as an example because it is easy to understand the problem of having it stored in several places.

I hope my answer can help you :)

**Comment by Jmaharman** [comment]
> I think this just illustrates how we need to revamp the docs to make it much clear as to what, where, when and how things are :-)

@isaacabraham do you think that would include how to compose multiple apps into the same site, as you mention in option 1?

Happy to read through any docs as they are written, my beginners view point may give you useful insight into those that are new to the stack.

> Alfonso tested it on fulma-demo, and you can have a look at the discussion for more information.
Great, thanks. This is a nice simple example of it's use, I'd always associated lazy to be part of some sort of "require" call, but this shows nicely how it would work with Fable.

Thanks @MangelMaxime, that's helped a lot.

**Comment by theimowski** [comment]
@Jmaharman can we close this issue?

**Comment by Jmaharman** [comment]
Sure thing
