### ISSUE TITLE
Using static routes does not work for parameterisation

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-template#377]
In the V2 template, we have a `Route` module with formal routes. In principle this is a good idea as it guarantees sync between routes on client and server. However I can't see how this would work for parameterised routes. If we can't get that to work, I think it would be better to remove this altogether.

What do other people think?

**Comment by isaacabraham** [comment]
cc: @theimowski @theprash @Krzysztof-Cieslak @Zaid-Ajaj

**Comment by olivercoad** [comment]
I don't think it's necessary to handle parameterised routes in the minimal template. Often APIs only need static routes and then just use query parameters and/or request body.

Also the `Route` module is currently the only thing in Shared.fs so if it's removed then some other placeholder shared code would have to be added.

> However I can't see how this would work for parameterised routes

Yes, having parameters in the path does make it harder to share code for the route (unless using an abstraction like Fable.Remoting).

However, even when the server and client need different code to define the route, it's still useful having them defined visually close together. It's much easier to ensure they are in sync when the server and client part of a route are defined right next to each other in the same module rather than in separate projects, even if it's not guaranteed that they'll be in sync.

**Comment by olivercoad** [comment]
I guess you could probably abuse `PrintfFormat` if you really wanted to avoid duplicating the route path:

```fsharp
// shared module Route
let helloWorldNameAge () : PrintfFormat<_,_,_,_,_> = "/name/%s/%i" //must be a function to keep generic types unconstrained

//saturn
getf (helloWorldNameAge()) (fun (name,age) -> ...)

//client
let getHelloWorld name age = Fetch.get<unit, string> (sprintf (helloWorldNameAge()) name age)
```

Not sure I'd recommend that though - what do you think @isaacabraham?

**Comment by isaacabraham** [comment]
For Fable Remoting this is, as you say, not needed. For the minimal template I just worry that leaving as-is will confuse people once they try to do a parameterised route.

**Comment by theimowski** [comment]
IMO it's ok to have it there even if it doesn't solve the parameterised routes issue. It also serves as a showcase of sharing code

**Comment by theimowski** [comment]
@isaacabraham how about creating a recipe that shows how to do this for minimal template?

**Comment by isaacabraham** [comment]
Let's leave it - closing this issue.
