### ISSUE TITLE
v2 - Fable compile error when adding any DU to shared code

### ISSUE THREAD

**Issue by theprash** [SAFE-Stack/SAFE-template#389]
1. dotnet new safe
2. Add any DU to the Shared.fs file, e.g. `type X = A | B`
3. dotnet fake build -t run

This results in a Fable compile error:

```
ERROR in ../Shared/Shared.fs
Module not found: Error: Can't resolve 'core-js/modules/es.function.name' in 'C:\temp\safe-template-bug\src\Shared'
 @ ../Shared/Shared.fs 1:0-42
 @ ./Index.fs
 @ ./App.fs
 @ ./Client.fsproj
```

I have node v14.5.0.

I have found that updating core-js from 3.3.2 to 3.6.5 (current latest) fixes the issue.

**Comment by theprash** [comment]
Actually, I can no longer fix the issue by upgrading core-js. I don't know why that worked once before. Investigating further.

**Comment by isaacabraham** [comment]
And I can't repro here either... :-/

**Comment by olivercoad** [comment]
Repros for me (tested on 94351e0bca5d4ae99802bdb8a566b65a186834d9)

Upgrading core-js did not fix the issue.

The issue seems to be that files in the shared project just can't see anything in node_modules (including core-js) because it's not in a parent directory.
Moving `package.json` (and `package-lock.json` and `node-modules`) to the root of the repo where it used to be fixes the issue.

It's not necessary to move `webpack.config.js` as well - you can prepend the scripts in `package.json` with `cd src/Client &&`.

**Comment by olivercoad** [comment]
Based on the above, I predicted that the client and shared test projects would also fail if I added DU to either of them but they don't. They both compile and run successfully, even with a DU in the (non-test) shared code.

It turns out `webpack.tests.config.js` does not use babel. If changed to use babel then they do fail, and `Client.Tests.fs` actually has another similar error:

```
ERROR in C:/Users/Oliver/Source/Repos/safe-template-test-389/tests/Client/Client.Tests.fs
Module not found: Error: Can't resolve 'core-js/modules/es.array.slice' in 'C:\Users\Oliver\Source\Repos\safe-template-test-389\tests\Client'
 @ C:/Users/Oliver/Source/Repos/safe-template-test-389/tests/Client/Client.Tests.fs 1:0-40
 @ C:/Users/Oliver/Source/Repos/safe-template-test-389/tests/Client/Client.Tests.fsproj
```

We should probably consider changing `webpack.tests.config.js` to use babel the same as `webpack.config.js` in order to catch similar problems in the future.

**Comment by Zaid-Ajaj** [comment]
> Moving package.json (and package-lock.json and node-modules) to the root of the repo where it used to be fixes the issue

@olivercoad I think this was indeed the issue, I've seen it a couple of times before when package.json files aren't in the root

**Comment by theprash** [comment]
I moved `package.json`, `package-lock.json` and `webpack.config.js` to the root and updated paths in `webpack.config.js`. I can confirm this fixed the issue for me as well. I think it makes more sense to keep these files together, and I think it's reasonable to keep them at the root as we had that in v1 of the template.

I suppose the issue comes from core-js or babel having an issue with reaching for code outside of its root directory on some machines.

I'll open a PR to make this change.

**Comment by klinki** [comment]
@theprash Hello, I just encountered this issue. Is it possible to solve it without having to move package.json to root directory? I would prefer to have frontend dependencies only in frontend directory.

**Comment by theprash** [comment]
@klinki Sorry, I never tried to solve it that way. I actually prefer all the dependencies to be managed in one place in the root directory, because `paket.dependencies` also contains front-end dependencies which must be in sync with the npm dependencies.
