### ISSUE TITLE
Consider removing ToDo from the full template

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-template#402]
The ToDo app has many good things:

* Gives users a ready-made app to play with - good for simple demos to colleagues etc.
* Serves an educational purpose - lets people learn from a simple base
* Provides a landing ground for recipes and enhancements e.g. https://safe-stack.github.io/docs/recipes/storage/use-litedb/

However, there's a second (and I would argue more important) use case that is missed here: **creating new applications**. To create a new app, you need to remove a number of types and files (in fact, I'm starting to think that we need a recipe for it!) and for a beginner this may be a bit of effort.

I think we have a few options:

1. Create a recipe (cheapest option but worst end-user experience for creating new apps).
2. Create a *third* template option i.e. full but no todo app (I would rather not do this)
3. Remove the ToDo app and move it into a standalone github repo / project which we could build all sorts of cool things as a demonstrator app, like SAFE Search and the Bookstore etc. (This is my personal preference).

**Comment by theprash** [comment]
I just timed how long it took me to remove the to-do app code from full template and it was 5 minutes. But I can probably do this quicker than most because:

- I've been involved with building the template so I've used it a lot and already know exactly where all the code is that I need to remove.
- I am very familiar with all the technologies and tools involved (F#, Elmish, Fable.Remoting, Expecto etc.) having worked with them full-time for years now.
- I use VsVim 😝

So I would estimate that for someone quite new to SAFE or this template, it would take at least 20 minutes to remove the same code and get everything compiling. That's a big inconvenience when making either a simple hello world or a new production app.

**Comment by isaacabraham** [comment]
If I think back to dotnet new Console etc. - they don't contain sample applications, they are designed to start a *new* app as quickly as possible.

**Comment by ChrSteinert** [comment]
+1 for VsVim btw. – no idea what I would do without it.

While I also like the idea of seperating samples and templates, I think that SAFE is special, because you will not add another `dotnet new SAFE.Server` or `dotnet new SAFE.Client` typically – do you?

Maybe a balanced approach would be to have the current ToDo app (with awesome and cool additions ;) ) as a "big" sample and have the Template stripped down even more, or, at least, not increase it's size.

**Comment by kulshekhar** [comment]
Would it be a good idea to document the steps one could take to convert a project, created using the minimal template, to a state where it'd be almost identical to the setup created by the standard template?

That would:
- avoid the need to create a new template
- keep the todo sample code for folks who are just testing this out (it is immensely helpful)
- give those who don't want a series of independent, optional commands to execute to get the project in exactly the state they want it in (without the todo code and fulma, for example)

The thinking is that those who want to start a proper project are likely already experienced enough with the SAFE stack that they could easily understand and follow the instructions to have a setup they want to start with, within a few minutes.

**Comment by theprash** [comment]
@kulshekhar I don't having a minimal to full recipe makes sense because it would take at least 10 times as long to do that compared to just deleting the to-do code from the full template. There are several big differences between the two versions. It's easier to start with full and delete what you don't need.

**Comment by theimowski** [comment]
What do you suggest trimming the sample code to for default option? How does the starting point after removing the TODO sample?

IMO the biggest advantage of having *any* sample application as a starting point of the default template is that it demonstrates how certain pieces fits together. A developer can get a big picture of SAFE just by browsing through the code:
* Understand Elmish just by looking at the Model, Msg and update functions in Client,
* Find out how communication is done between Client and Server,
* How the unit tests are configured and what functionality they test.

Following opinion is not backed by any observations, but I think there are users that care little about the docs after they get to the `dotnet new safe` point, and rely strictly on what's in the codebase.

Anyway I understand the pain of removing boilerplate after creating the template.
If we remove the TODO list from default option we need to make sure that the "quick start" and "introduction" sections in docs refer to and showcase the example code clearly.
