### ISSUE TITLE
Set `SupportedPlatform` in .NET 5 Template

### ISSUE THREAD

**Issue by Shmew** [SAFE-Stack/SAFE-template#405]
Reading Immo's article [The future of .NET Standard](https://devblogs.microsoft.com/dotnet/the-future-of-net-standard) a feature caught my eye that I thought could be nice to have in the future. The attributes in the BCL allows authors to define supported platforms, and platform specific APIs are similarly marked with this attribute. 

So whenever y'all release a .NET 5 targeted template you could set `<SupportedPlatform Include="fable" />` in the client project. I think this will give users an error faster than trying to compile with Fable and then realizing it's unsupported. I don't think this will occur frequently at all, and it will mostly happen to very new users, but that's also the ones we all want to have a smooth experience. If there's ever a `Node.js` or `Electron` template those APIs could also take advantage of this system.

I'm also curious if there's a way to configure things so that it can work with shared files somehow. Anyways, just figured it would be a good idea to mention this for the future.

**Comment by theimowski** [comment]
@alfonsogarciacaro do you think this would work with Fable?
I don't fully understand how these platforms are defined - is `browser` reserved for Blazor?

**Comment by Shmew** [comment]
That's my understanding

**Comment by alfonsogarciacaro** [comment]
Not sure, although I doubt it. It's a complicated topic, conceptually what Fable tries to do is precisely to move F# out of .NET into another platform (JS). But technically and as long as we use FCS to parse the F# code we need to always reference the basic .NET assemblies even in the REPL. Besides that, I think it will be difficult to take advantage of the `SupportedPlatform` item because:

- In the article Immo says they don't consider webassembly a platform, but the browser. A similar reasoning can be applied to Fable, it's just a compiler that turns F# code into JS. But then this can be run anywhere where JS code is accepted, be it the browser, node, react native, etc. So not sure what would be the platform in this case.
- For convenience, we usually target netstandard2.0 in Fable projects (and we do use netstandard2.0 assemblies in the repl) but Fable is not even close to cover all netstandard2.0 APIs so we cannot consider it a proper target framework.
- Immo and his team have access to the BCL code so they can mark the unsupported APIs with `[UnsupportedOSPlatform("browser")]` as he says in the article. We cannot do that, so even if "fable" could be considered a target platform, users wouldn't get compiler warnings for unsupported APIs. (They do get warnings from Fable itself when a replacement to a call to the BCL cannot be found.)

**Comment by theimowski** [comment]
Thanks for the detailed explanation. 
Given the above I'll close the issue for now, but feel free to reopen it should there arise any new insights on that topic
