### ISSUE TITLE
[NRE] It happens with Giraffe and NPM template

### ISSUE THREAD

**Issue by t-smirnov** [SAFE-Stack/SAFE-template#42]
NRE happens here:
```f#
 task {
        let! counter = getInitCounter()
        >>> return! Successful.OK counter next ctx
    }
```
here's some stacktrace:
```
Exception has occurred: CLR/System.NullReferenceException
Exception thrown: 'System.NullReferenceException' in FSharp.Core.dll: 'Object reference not set to an instance of an object.'
   at Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.UnboxGeneric[T](Object source)
   at Giraffe.Negotiation.HttpContext.NegotiateAsync(HttpContext this, Object responseObj)

```

![nre-fsharp-safe-template](https://user-images.githubusercontent.com/17054766/36641700-4aa25f38-1a45-11e8-9a20-858b6576c4d8.PNG)

**Comment by forki** [comment]
/cc @dustinmoris

Am 25.02.2018 14:03 schrieb "Tim" <notifications@github.com>:

**Comment by t-smirnov** [comment]
additionally it occurs with latest netcore, win10, without VS installation

**Comment by theimowski** [comment]
I can reproduce, looks to me like newest Giraffe 1.1.0 has issues with unboxing integer type for the response in: `return! Successful.OK 42 next ctx` - waiting for @dustinmoris to comment

**Comment by dustinmoris** [comment]
Hi,

I've tested the following with the latest Giraffe 1.1.0 and it worked perfectly fine for me:

```fsharp
route "/int1" >=> Successful.OK 42
route "/int2" >=> (fun next ctx -> task { return! Successful.OK 42 next ctx })
```

My guess is that you haven't registered the default Giraffe dependencies which make sure that you have a valid JSON and XML serializer as dependencies:

```fsharp
let configureServices (services : IServiceCollection) =
    // Add Giraffe dependencies
    services.AddGiraffe() |> ignore
```

With Giraffe 1.0.0 I've moved away from `customJson` and other custom this and that functions in favour of registering serializers through ASP.NET Core's service collection, which makes it possible to configure one JSON serializer or one XML serializer for an entire Giraffe application, so that it works across the board, including `negotiate` and the status response helpers like `Successful.OK`.

It's been documented here: https://github.com/giraffe-fsharp/Giraffe/blob/master/DOCUMENTATION.md#plugging-giraffe-into-aspnet-core

Let me know if this was the issue otherwise please open a new issue in the Giraffe repo with a repro project! Thank you!

**Comment by t-smirnov** [comment]
Hi, @dustinmoris , thanks for help, but for now - api/init method responded as 
```
Error occured while trying to proxy to: localhost:8080/api/init
``` 

hmm..

**Comment by Zaid-Ajaj** [comment]
@t-smirnov Isn't this a webpack-dev-server error though? Because webpack-dev-server is delegating all requests to the actual backend

**Comment by dustinmoris** [comment]
@t-smirnov Not sure what this is now. I always find the best way to diagnose an issue is to strip away everything else and just test the core first, then slowly start adding stuff to see at which layer you are introducing an error.

**Comment by t-smirnov** [comment]
thanks @dustinmoris 
For now all works fine :)

finally, NRE caused by template hasnt `ConfigureServices` method, are you receiving PR? (im just beginner in open source things)

**Comment by dustinmoris** [comment]
Perfect, glad it works for you now @t-smirnov!

If the template is missing `ConfigureServices` then you can send me us a PR in the [template repo](https://github.com/giraffe-fsharp/giraffe-template). However, I think the latest template has it in all its variations. Maybe the SAFE template is missing it?

**Comment by t-smirnov** [comment]
@dustinmoris yep, I mean SAFE template ofc
