### ISSUE TITLE
Add ARM template and routine for Azure deployment

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-template#51]
We should add the capability to easily deploy to Azure using one of either git-based deployments (perfect for quickly getting results, but not necessarily the best for a production CI system), or Kudu's zip deploy feature.

Also we should include an ARM template to allow users to quickly create the resources required in Azure.

One thing that will need to be done as part of this is consider how and where the app locates the static content - currently it's designed to look in the `..\client` folder etc. but this should probably be replaced by the app copying the js bundle and html files into the public folder on the server.

**Comment by theprash** [comment]
Perhaps the static content path should be a configurable in the server so that we can create a self contained server and client deployment. This gives more flexibility for different deployment options and should avoid breaking the existing Docker deploy part of the FAKE script, which is only present if you use the template with the Docker option.

**Comment by theimowski** [comment]
Closed by #65
