### ISSUE TITLE
Config option for azure auto deployment 

### ISSUE THREAD

**Issue by darren-m-kim** [SAFE-Stack/SAFE-template#520]
Can there be a config option for azure deployment? Currently once it is deployed by `dotnet azure ..`, its minimum cost is about more than $50 per month at least (without meaningful traffic).

**Comment by reigam** [comment]
`dotnet run Azure` will deploy to a [free tier. ](https://azure.microsoft.com/en-us/pricing/details/app-service/windows/)
You can deploy 10 Apps, get a shared core with 60 CPU min/d, 1GB Ram and 1GB Storage. 
Great for fast deployment and testing, but I agree that the higher tiers are much to expensive for non commercial use.

**Comment by reigam** [comment]
Strange. Are you still on your free trial? (200USD to spend on services?). Didn't you have to agree on a payment first?
I uploaded several apps and always ended up on (F1:Free). 
Unfortunately that's all I can say about this topic, since that's all of my knowledge about azure and It's deeper workings. 

I do all of my testing and deployment with docker images, which I host on a cloud server (~7USD/month).

Hope somebody with more azure knowledge can help you out.

**Comment by theprash** [comment]
For the app service the template does not specify a SKU so we end up with the Farmer default which is the free tier. But Farmer also adds a corresponding Application Insights by default which could incur a small cost if the site is used. The app insights can be disabled if necessary:

```fsharp
    let web = webApp {
        ...
        app_insights_off
    }
```

I'd suggest closing this issue unless further clarification is provided, i.e. what exactly is costing money in the deployment and what is the suggested change?
