### ISSUE TITLE
Template appears to be incompatible with latest version of node.js 

### ISSUE THREAD

**Issue by bmilhollin** [SAFE-Stack/SAFE-template#538]
When installing the SAFE template on a new computer, I downloaded the LTS version of node.js and was not able to build the sample application.  The error indicated it was a node.js issue.  Several co-workers had run into this issue and recommended I remove v18 and install v16, and this took care of the issue.

**Comment by jcmrva** [comment]
Is this the error you're getting? 

> Starting target 'InstallClient'
> .> "C:\Program Files\nodejs\npm.CMD" install (In: false, Out: false, Err: false)
> npm ERR! Unexpected token '.'

> 33 verbose stack C:\ProgramData\nvm\v18.12.1\node_modules\npm\node_modules\libnpmfund:1
> 33 verbose stack ../workspaces/libnpmfund
> 33 verbose stack ^
> 33 verbose stack
> 33 verbose stack SyntaxError: Unexpected token '.'

Which version of v16 fixed it? I tried 16.18.1 but no change.

**Comment by olivercoad** [comment]
@jcmrva I think you're actually running into an issue with nvm https://github.com/coreybutler/nvm-windows/issues/814

Hi @bmilhollin, thanks for opening an issue. When you make reports like this it would be useful if you could paste some actual logs so that we don't have to guess that the issue might be. If it's not the same issue as above, is it something like this?

```
Starting target 'InstallClient'
.> "/home/oliver/.nvm/versions/node/v18.12.1/bin/npm" install (In: false, Out: false, Err: false)
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: undefined
npm ERR! notsup Not compatible with your version of node/npm: undefined
npm ERR! notsup Required: {"node":"~16","npm":"~8"}
npm ERR! notsup Actual:   {"npm":"8.19.2","node":"v18.12.1"}

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/oliver/.npm/_logs/2022-11-05T23_36_04_923Z-debug-0.log
```

If so, that's expected and is just npm enforcing that the versions of npm and node are the same as what's requested in `package.json`. That just helps increase consistency by making sure people use the same major versions. I believe the latest version of the safe template is actually compatible with node 18, so you can just change the version numbers or even just remove the `engines` part in the `package.json` and it should work fine.

**Comment by teknikal-wizard** [comment]
@bmilhollin could you let us know if the above comment addresses your issue? If so I will close off the ticket, thanks!

**Comment by bmilhollin** [comment]
Yes, thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
