### ISSUE TITLE
Make Saturn the default server

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-template#54]

**Comment by Zaid-Ajaj** [comment]
But why?

**Comment by Krzysztof-Cieslak** [comment]
To have S in front. ;-)

Also, it's just a good choice but I'm biased ;-)

**Comment by theimowski** [comment]
I don't yet have a strong opinion on that. Might be because of I still don't feel prominent in Saturn. 
Anyway curious to hear others' take on it

**Comment by kfrie** [comment]
I have been on-boarding the stack since 01/2018 and just got used to Giraffe. However I think Saturn could be better marketable to an application developer/team who is encountering the stack for the first time, especially if they are new to F#.

Why not decide by some kind of more objective measures like time, money and value? For instance, I judiciously track my time working on things including research and just getting my head around a new framework/library/set of abstractions and understand it well enough to use with confidence takes me usually 30-100h, given it is within a ecosystem I know my way around already. 

I could have a team that needs training and consulting, where I need to get every single team member on board with the new set of abstractions. This would cost some more of my time, my team members time and possibly money for buying external consultancy.  

I really cannot rate on my own if Saturn beats the others in those terms, I just think this could be the right way of thinking about choosing the standard backend technology for SAFE. And that it then is fixed for at least some years. I think after all the crazy NETCore/NETStandard evolution has been finally coming to a good end, some people might just want to have some stability for a few years in their technology stack  and use their time to create and sell applications for a living. But that could also be just me, I don't know 😄

**Comment by haf** [comment]
I think this is shit.

**Comment by Krzysztof-Cieslak** [comment]
Cheers
