### ISSUE TITLE
Look at files in Client.fsproj that probably are not required to be

### ISSUE THREAD

**Issue by martinbryant** [SAFE-Stack/SAFE-template#580]
The following files are noted in the Client.fsproj that are dev/build specific and do not affect the building of the Client project.

- vite.config.mts 
- tailwind.config.js 
- postcss.config.js

We should look to get input from @MangelMaxime about this and if we can remove them if there is no reason to leave them

**Comment by MangelMaxime** [comment]
Hello,

Fable only needs the `.fs` files to be include in the project file.

Adding others files likes:

```xml
        <None Include="postcss.config.js" />
        <None Include="tailwind.config.js" />
        <None Include="index.html" />
        <None Include="paket.references" />
```

Is a matter of preference.

Personally, because I never use the Solution Explorer view, I never add this files in my project files. But I know people who use Solution Explorer instead of File Explorer, includes this files so they can have an easy access to them.

The decision on this subject, depends on how you think people will consume the template and use it.

**Comment by theprash** [comment]
These are there because I am intentionally including them to make the files easily available in Visual Studio. Is there some reason to remove them?

**Comment by RicoSaupe** [comment]
Updated the proj and sln files in my pr. Please have a look and approve.
