### ISSUE TITLE
watch tests in browser vs run tests with node

### ISSUE THREAD

**Issue by Freymaurer** [SAFE-Stack/SAFE-template#637]
Hey i am curious and wanted to learn something. In the build project you use the fable mocha browser test suit for `watchruntests` vs the `npx mocha`, which uses node.js for the runtestsheadless.

I just ran into some issues with this, as i used a library for mocking up data, which uses node.js functions (which wasn't obvious to me). 

Therefore the tests ran successfully with run tests and were not able to run for watch tests.

Can you explain this design decision to me? Really interested in your answer as i am still evaluation on how to move forward in my case.

**Comment by Larocceau** [comment]
Hi @Freymaurer! Thank you for the question. When we initially added the tests, we used the Fable mocha test suite for our Client test, to keep the test execution as similar as possible to the live scenario. In that way, we can test for any possible interplay with fable too.

Later, we found that the template had started to deviate a bit from the tests, but found that out pretty late because we generally don't run them (the tests included in the template are there as a sample, not as a way for us to test the code). We therefore included the tests in our GitHub pipeline, so we would be notified if we broke them. The simplest way to do this, is using Node.

I'm closing the ticket for now, but feel free to re-open if you need more information!
